# Generated by Django 5.2.14 on 2026-05-25 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_risco', models.BooleanField(default=False)),
                ('gestante', models.BooleanField(default=False)),
                ('alergias', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='pessoas.paciente')),
            ],
        ),
    ]
