# Generated by Django 5.2.14 on 2026-05-25 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimentos', '0001_initial'),
        ('pessoas', '0001_initial'),
        ('unidades', '0001_initial'),
        ('vacinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroVacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateField()),
                ('dose', models.CharField(max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atendimentos.atendimento')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacinas.lotevacina')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.paciente')),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.profissionalsaude')),
                ('unidade_saude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidades.unidadesaude')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacinas.vacina')),
            ],
        ),
    ]
