# Generated by Django 5.2.14 on 2026-05-25 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('fabricante', models.CharField(max_length=200)),
                ('doenca_prevenida', models.CharField(max_length=200)),
                ('quantidade_doses', models.IntegerField()),
                ('intervalo_dias', models.IntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoteVacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50)),
                ('data_validade', models.DateField()),
                ('quantidade_disponivel', models.IntegerField()),
                ('unidade_saude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='unidades.unidadesaude')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='vacinas.vacina')),
            ],
        ),
    ]
