"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import environ
import os
env = environ.Env()
environ.Env.read_env(os.path.join(os.path.dirname(os.path.dirname(__file__)), '.env'))
SECRET_KEY = env('SECRET_KEY')
DEBUG = env.bool('DEBUG', default=True)

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = [
    host.strip()
    for host in env('ALLOWED_HOSTS', default='localhost,127.0.0.1,10.116.10.101').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'apps.pessoas',
    'apps.unidades',
    'apps.vacinas',
    'apps.perfis',
    'apps.calendario',
    'apps.atendimentos',
    'apps.registros',
    'apps.campanhas',
    'apps.notificacoes',
    'apps.situacao',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


ORACLE_WALLET_DIR = env('ORACLE_WALLET_DIR', default='')
ORACLE_OPTIONS = {}

if ORACLE_WALLET_DIR:
    wallet_path = ORACLE_WALLET_DIR
    if not os.path.isabs(wallet_path):
        wallet_path = os.path.join(BASE_DIR, wallet_path)

    ORACLE_OPTIONS = {
        'config_dir': wallet_path,
        'wallet_location': wallet_path,
    }

    ORACLE_WALLET_PASSWORD = env('ORACLE_WALLET_PASSWORD', default='')
    if ORACLE_WALLET_PASSWORD:
        ORACLE_OPTIONS['wallet_password'] = ORACLE_WALLET_PASSWORD

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': env('ORACLE_DSN'),
        'USER': env('ORACLE_USER'),
        'PASSWORD': env('ORACLE_PASSWORD'),
        'HOST': '',
        'PORT': '',
        'OPTIONS': ORACLE_OPTIONS,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
