# Generated by Django 5.2.14 on 2026-05-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=300)),
                ('bairro', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('horario_funcionamento', models.CharField(max_length=100)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
    ]
