# Generated by Django 5.2.14 on 2026-05-26 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendario', '0001_initial'),
        ('pessoas', '0001_initial'),
        ('vacinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituacaoVacinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('em_dia', 'Em Dia'), ('pendente', 'Pendente'), ('atrasado', 'Atrasado')], max_length=20)),
                ('data_verificacao', models.DateTimeField(auto_now=True)),
                ('observacao', models.TextField(blank=True)),
                ('calendario_vacinal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendario.calendariovacinal')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.paciente')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacinas.vacina')),
            ],
        ),
    ]
