# Generated by Django 5.2.14 on 2026-05-25 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioVacinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade_minima_meses', models.IntegerField()),
                ('idade_maxima_meses', models.IntegerField(blank=True, null=True)),
                ('publico_alvo', models.CharField(max_length=200)),
                ('dose_recomendada', models.CharField(max_length=50)),
                ('obrigatoria', models.BooleanField(default=False)),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarios', to='vacinas.vacina')),
            ],
        ),
    ]
